### ISSUE TITLE
What's the real LICENSING 

### ISSUE THREAD

**Issue by jiacheo** [jianzhnie/Chinese-Guanaco#1]
> We release the resources associated with QLoRA finetuning in this repository under `MIT license`. In addition, we release the Guanaco model family for base LLaMA model sizes of 7B, 13B, 33B, and 65B. These models are intended for purposes in line with the LLaMA license and require access to the LLaMA models. 

but the LICENSE file say it's `Apache License 2.0`

**Comment by jianzhnie** [comment]
Chinese-Guanaco is released under the Apache 2.0 license
