### ISSUE TITLE
合并代码还有一个错误，中间少了一个变量

### ISSUE THREAD

**Issue by apachemycat** [jianzhnie/Chinese-Guanaco#12]
刚才还发现一个问题，少个参数，导致保存模型的逻辑没生效，代码如下：
    **parser.add_argument('--load_8bit', type=bool, default=False)**

    args = parser.parse_args()

    apply_lora(args.base_model_path,args.lora_path,**args.load_8bit,** args.target_model_path,
               args.save_target_model)

**Comment by jianzhnie** [comment]
bugs have solved: https://github.com/jianzhnie/Efficient-Tuning-LLMs/blob/main/utils/apply_lora.py#L85
