### ISSUE TITLE
RuntimeError: probability tensor contains either `inf`, `nan` or element < 0

### ISSUE THREAD

**Issue by weifan-zhao** [jianzhnie/Chinese-Guanaco#5]
<img width="1139" alt="截屏2023-06-13 09 29 19" src="https://github.com/jianzhnie/Chinese-Guanaco/assets/48010074/711c1d47-a7b6-4480-a97f-22d264a4ceff">

**Comment by jianzhnie** [comment]
which model do you run? the base_model and adapters

**Comment by weifan-zhao** [comment]
the base model: vicuna-13b
adapters: trained with finetune.sh(dataset_format: alpaca-cleaned)

**Comment by weifan-zhao** [comment]
> which model do you run? the base_model and adapters

the base model: vicuna-13b
adapters: trained with finetune.sh(dataset_format: alpaca-cleaned)

**Comment by jianzhnie** [comment]
```sh
python generate_server.py \
    --model_name_or_path decapoda-research/llama-7b-hf \
    --lora_model_name_or_path  tloen/alpaca-lora-7b \
    --load_8bit
```
run add test this scripts and find the bugs

**Comment by weifan-zhao** [comment]
> ```shell
> python generate_server.py \
>     --model_name_or_path decapoda-research/llama-7b-hf \
>     --lora_model_name_or_path  tloen/alpaca-lora-7b \
>     --load_8bit
> ```
> 
> run add test this scripts and find the bugs

I ran this script with the same error as before
