### ISSUE TITLE
data_utils.py 是不是有问题？

### ISSUE THREAD

**Issue by wgzhendong** [jianzhnie/Chinese-Guanaco#59]
348         train_dataset, eval_dataset = split_train_eval(
349             dataset,
350             do_eval=args.do_eval,
351             eval_dataset_size=args.eval_dataset_size,
352             max_eval_samples=args.max_eval_samples,
353             do_train=args.do_train,
354             max_train_samples=args.max_train_samples,
355         )
356         if train_dataset:
357             print('=' * 80)
358             print('loaded dataset:', dataset_name, 'train data size:',
359                   len(train_dataset))
360             train_datasets.append(train_dataset)
361         if eval_datasets:
362             print('=' * 80)
363             print('loaded dataset:', dataset_name, 'eval data size:',
364                   len(eval_dataset))
365             eval_datasets.append(eval_dataset)

361行，eval_datasets --> eval_dataset ???

**Comment by jianzhnie** [comment]
感谢，Bug 已修复， 这个issus 关闭了
