### ISSUE TITLE
RuntimeError: probability tensor contains either `inf`, `nan` or element < 0

### ISSUE THREAD

**Issue by weifan-zhao** [jianzhnie/Chinese-Guanaco#6]
> ```shell
> python generate_server.py \
>     --model_name_or_path decapoda-research/llama-7b-hf \
>     --lora_model_name_or_path   @tloen/alpaca-lora-7b \
>     --load_8bit
> ```
> 
> run add test this scripts and find the bugs

I ran this script with the same error as before

**Comment by Macvh** [comment]
I encountered the same problem, how did you solve it?
