### ISSUE TITLE
微调训练失败

### ISSUE THREAD

**Issue by QJShan** [jianzhnie/Chinese-Guanaco#63]
你好 大佬博主！
在使用lora微调的时候出现一下loss异常的原因可能是什么。
pytorch ：2.0
在数据预处理阶段 将输入以及padding处的label标记为-100，在最后的计算交叉损失中忽略-100标志位的损失。
![image](https://github.com/jianzhnie/Efficient-Tuning-LLMs/assets/131762142/e0524e4e-b335-4a4b-bb82-4050dfed12b9)

**Comment by jianzhnie** [comment]
学习率设置的太高了

**Comment by QJShan** [comment]
> 学习率设置的太高了

5e-3还是太高了吗 一般设置多少 我同样的参数同样的数据集在glm-6b中训练没问题

**Comment by QJShan** [comment]
> 学习率设置的太高了
我刚入门nlp领域，有劳大佬你指点一二，学习率的设置有什么样技巧
我这边将学习率设置称为了5e-5  训练一定step后 loss又突然上升
![image](https://github.com/jianzhnie/Efficient-Tuning-LLMs/assets/131762142/0b058117-b9c8-40ee-9168-271bd65d9ff8)

**Comment by jianzhnie** [comment]
可能和你的数据集有关，你训练 epochs 太多，导致过拟合
