### ISSUE TITLE
[问题]有关训练可视化

### ISSUE THREAD

**Issue by RickMeow** [jianzhnie/Chinese-Guanaco#92]
感谢您对于项目的贡献！

**问题描述**

对于微调训练过程来说，Efficient-Tuning-LLMs有 可视化实时训练进展、曲线的方式吗？

**期待您的回复！**

**Comment by jianzhnie** [comment]
Efficient-Tuning-LLMs 默认使用 wandb 进行可视化

**Comment by RickMeow** [comment]
好的，非常感谢
